version: "3.9"

services:

  static_auth:
    image: dkllrjr/static_auth:0.1.1
    stdin_open: true
    tty: true
    restart: unless-stopped
    entrypoint: ./app
    environment:
      SA_SIGNUP: "${SA_SIGNUP}"
      SA_SECRET_KEY: "${SA_SECRET_KEY}"
      SA_DATABASE: "${SA_DATABASE}"
      SA_URL: "${SA_URL}"
    volumes:
      - ./website:/static_auth/website
      - ./database:/static_auth/database
    ports:
      - 8080:8080

